spring.application.name=personal
server.port=8089


#MongoDB connection details
spring.data.mongodb.uri=mongodb://localhost:27017/expense_tracker
spring.data.mongodb.database=expense_tracker

# Plaid (development)
plaid.base-url=https://sandbox.plaid.com
plaid.client-id=696daa416d8f210022b23c56
plaid.secret=d058d142b63f0ff9d97fa7f308448e
plaid.client-name=Expense Tracker
plaid.country-codes=US
plaid.products=transactions
plaid.language=en
